apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - nodePort: 31317
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend