name: Docker Images

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Backend docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        tags: ghcr.io/seanemac/simple-ci-cd/backend:latest
        push: true

    - name: Build the Frontend docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        tags: ghcr.io/seanemac/simple-ci-cd/frontend:latest
        push: true